/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CtrRecibo;
import Model.Recibo;
import java.io.InputStream;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author hen_r
 */
public class exibeRecibos extends javax.swing.JFrame {

    /**
     * Creates new form exibeRecibos
     */
    public exibeRecibos() {
        initComponents();
        icone();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        edtCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Histórico de Recibos");
        setExtendedState(6);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nº do Recibo:");

        jLabel2.setText("Nome do Cliente:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search.png"))); // NOI18N
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID do Recibo", "Cliente", "Contato", "Telefone", "E-mail", "Data de Emissão", "Status do Pagamento", "Previsão de Pagamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edtNome))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(edtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(jLabel2))
                        .addGap(0, 151, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pagamento.png"))); // NOI18N
        jMenu1.setText("Alterar Status de Pagamento");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/recibop.png"))); // NOI18N
        jMenu2.setText("Reemissão de Recibo");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id = edtNome.getText();
        String cliente = edtCliente.getText();
        
        if(id.equals("") && cliente.equals("")){
            JOptionPane.showMessageDialog(null,"Nenhum dado digitado!");
            limparTabela();
            preencherTabela();
        } else {
            if (id.equals("")){
                id = "0";
            }
            if(cliente.equals("")){
                cliente = "0";
            }
                 
            //JOptionPane.showMessageDialog(null,id+cliente);
        
            limparTabela();
            resultadoBusca(id,cliente);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_formWindowActivated

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        CtrRecibo r = new CtrRecibo();
        int linhaSel; //variavel que recebera a linha(estudante) da tabela selecionada
        int id; //variavel que recebera o id do estudante selecionado

        linhaSel = jTable1.getSelectedRow();  //variavel 'linhaSel' recebera a linha da tabela selecionada 

        if(linhaSel == -1){
            JOptionPane.showMessageDialog(null,"Nenhum recibo selecionado!");
        } else {
            id = (int) jTable1.getValueAt(linhaSel,0); //variavel 'id' recebera o valor das coordenadas selecionada(linhaSel e coluna zero para receber o id do estudante) 
        
            try{ 
                if (JOptionPane.showConfirmDialog(null,"Deseja realmente alterar o status desse recibo?")==JOptionPane.OK_OPTION){ //notificação que pergunta se o usuario realmente quer excluir o estudante selecionado
                    try{
                        if(r.editaStatus(id)==true){ //envia a variavel 'id' para o metodo deletaEstudante na classe Controle)
                            JOptionPane.showMessageDialog(null,"Recibo pago!"); //abrirá uma janela informando que o estudate foi deletado com sucesso
                        }
                    } catch (Exception e){
                        JOptionPane.showMessageDialog(null, "Erro ao alterar o status!\nERRO:"+e.getMessage()); //caso ocorra algum erro, abrirá uma janela informando que aconteceu algo de errado e o erro que ocorreu  
                    }    
                }
            
            } catch (Exception e){
                JOptionPane.showMessageDialog(null,"ERRO:"+e); //caso nao seja selecionada nenhuma linha da tabela, abrira uma tela de notificação infromando que o usuário não selecionou nenhum estudante (linha)
            }
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        int linhaSel; //variavel que recebera a linha(estudante) da tabela selecionada
        int id; //variavel que recebera o id do estudante selecionado

        linhaSel = jTable1.getSelectedRow();  //variavel 'linhaSel' recebera a linha da tabela selecionada

        if(linhaSel == -1){
            JOptionPane.showMessageDialog(null,"Nenhum recibo selecionado!");
        } else {
            Recibo recibo = new Recibo();
            
            id = (int) jTable1.getModel().getValueAt(jTable1.getSelectedRow() ,0);
            String cliente = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow() ,1);
            String contato = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow() ,2);
            String telefone = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow() ,3);
            String email = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow() ,4);
            
            recibo.setIdrecibo(id);
            recibo.setCliente(cliente);
            recibo.setContato(contato);
            recibo.setTelefone(telefone);
            recibo.setEmail(email);
                
            try {
                Model.DAO bd = Model.DAO.getInstancia();
                Connection con;
                con = bd.getConexao();
                InputStream fonte = gerarReciboo.class.getResourceAsStream("/Relatórios/report2.jrxml");
                JasperReport report = JasperCompileManager.compileReport(fonte);
                Map parametros = new HashMap();
                parametros.put("id", id);
                parametros.put("cliente", cliente);
                parametros.put("contato", contato);
                parametros.put("telefone", telefone);
                parametros.put("email", email);
                JasperPrint print = JasperFillManager.fillReport(report, parametros, con);
                JasperViewer.viewReport(print, false);
            } catch (JRException ex) {
                Logger.getLogger(gerarReciboo.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Erro ao gerar o recibo!");
            }
                
        }
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exibeRecibos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exibeRecibos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exibeRecibos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exibeRecibos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exibeRecibos().setVisible(true);
            }
        });
    }
    
    public void preencherTabela(){ //metodo que preenche a tabela
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        DefaultTableModel tabela; //cria o objeto 'tabela' da coleção DefaultTableModel
        tabela = (DefaultTableModel) jTable1.getModel(); //cria o objeto 'tabela'
        for(Recibo r: CtrRecibo.exibeRecibos()){ 
            tabela.addRow(new Object[]{ //adiciona linha na tabela
                r.getIdrecibo(), //preenche coluna ID
                r.getCliente(), //preenche coluna titulo
                r.getContato(), //preenche coluna id do exemplar
                r.getTelefone(), //preenhce coluna nome do estudante
                r.getEmail(),
                formato.format(r.getData()),
                r.getStatus(),
                r.getPrevisao(),
            });
       }
    }
    
    public void resultadoBusca(String id, String cliente){ //metodo que preenche a tabela
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        CtrRecibo ctrrecibo = new CtrRecibo();

        if(ctrrecibo.procuraRecibo(id, cliente).isEmpty()){
            limparTabela();
            JOptionPane.showMessageDialog(null, "Nenhum recibo encontrado!");
            preencherTabela();
        } else {
            DefaultTableModel tabela; //cria o objeto 'tabela' da coleção DefaultTableModel
            tabela = (DefaultTableModel) jTable1.getModel(); //cria o objeto 'tabela'
            for(Recibo r: ctrrecibo.procuraRecibo(id, cliente)){ //laço que preenche a tabela com cada elemento da lista vinda do médoto exibeEmprestimo da classe Controle
                tabela.addRow(new Object[]{ //adiciona linha na tabela
                    r.getIdrecibo(), //preenche coluna ID
                    r.getCliente(), //preenche coluna titulo
                    r.getContato(), //preenche coluna id do exemplar
                    r.getTelefone(), //preenhce coluna nome do estudante
                    r.getEmail(),
                    formato.format(r.getData()),
                    r.getStatus(),
                    r.getPrevisao(),
                });
            }
        }
    }
    
    public void limparTabela(){
        DefaultTableModel tabela = (DefaultTableModel)jTable1.getModel();
        tabela.setNumRows(0);
    }
    
    public void icone(){
        this.setIconImage(new ImageIcon(getClass().getResource("iconC.png")).getImage());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField edtCliente;
    private javax.swing.JTextField edtNome;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
